### ISSUE TITLE
Estimating Student-t degrees of freedom parameter

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/Bayesian-Unobserved-Component-Models#14]
- [x] present estimation of a degrees of freedom parameter of an $N$-variate Student-t distribution modelled as the IG2-scale mixture of normal.
- [x] write a short note
- [x] a quick derivation or full conditional posterior presentation
- [x] an **R** function with the sampler
- [x] include your name in the author list

**Comment by bgussen** [comment]
Hey Tomasz, 

I've now submitted a pull request on the same. 

Regards, 
Gus

**Comment by bgussen** [comment]
Hi Tomasz, 

Thanks for the feedback. I'll go ahead and close this issue in preparation for submitting the final report. 

Regards, 
Ben
