### ISSUE TITLE
Conditional heteroskedasticity

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/Bayesian-Unobserved-Component-Models#15]
- [x] present the extension of the full conditional posterior distributions for the parameters of the baseline model given that the shocks $\epsilon_t$ is heteroskedastic with conditional variances $\sigma_t^2$
- [x] write a short note
- [x] a quick derivation or full conditional posterior for $T$-vector $\tau$
- [x] an **R** function with the sampler for full conditional posterior for $\tau$
- [x] include your name in the author list

**Comment by yufeimichelle** [comment]
All tasks are done in commit 35d3117d8f24954b310ec4b219eae0d3c656abba

**Comment by donotdespair** [comment]
OK, thanks @yufeimichelle Now you have to create and submit a pull request from your commit :)

**Comment by yufeimichelle** [comment]
My submission for Modelling Conditional heteroskedasticity part is now commit in https://github.com/donotdespair/Bayesian-Unobserved-Component-Models/commit/932e169688a5c06a9ee8e2bdc3055bde8f7dd2fa

**Comment by donotdespair** [comment]
Hey @yufeimichelle this is not a submission to the learning repo. You are only pushing commits to the repository you forked. That on is yours and has little to do with the learning repo. You must create a pull request and that submits your contributions to my repository.

Greetings, Tomasz

**Comment by donotdespair** [comment]
Hey @yufeimichelle This is a nice contribution! Thank you so much! I copy/pasted your text, corrected the typos and the code and submitted directly to the master branch as you can see above. Greetings, Tomasz
