### ISSUE TITLE
Simulation smoother and precision sampler

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/Bayesian-Unobserved-Component-Models#4]
- [x] describe what's the idea for using the Simulation smoother and precision sampler
- [x] provide an **R** function for the implementation of the precision sampler (a random number generator from a multivariate normal with a band precision matrix) Copy/paste/adjust my code. And describe a bit.
- [x] write a short note
- [x] a quick derivation or full conditional posterior presentation
- [x] an **R** function with the sampler
- [x] include your name in the author list

**Comment by JimmyYang917** [comment]
Hi @donotdespair 

Hope you are doing well

All points are carefully done, please remind me if any changes need to update.

Kinds regards

Yuqiao

**Comment by donotdespair** [comment]
Hey @JimmyYang917 

This is cool! A really good one! I implemented some editing changes. BTW may I ask if you copy/pasted my code from the article from **RcppGallery**? I am asking as that code was published under licence. We can use it here but we need to acknowledge this fact. Otherwise, stealing code is illegal :) Just please write me here if this was the case and I'll implement further changes.

Greetings,

Tomasz
