### ISSUE TITLE
Estimating the initial condition prior scale

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/Bayesian-Unobserved-Component-Models#8]
- [x] put a prior on the prior scale of $\tau_0$ and present its full conditional posterior distribution with an **R** function executing this sampler. The prior structure should be:
$\\tau|s \sim\mathcal{IG}2(\underline{\tau}, s^2)$
$s^2\sim\mathcal{IG}2(\underline{s},\underline{\nu})$
- [x] write a short note
- [x] a quick derivation or full conditional posterior presentation
- [x] an **R** function with the sampler
- [x] include your name in the author list

**Comment by russellyang728** [comment]
hi @donotdespair,

are the two \tao in prior structure \tao_0 actually? since \tao is a vector.
